language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: iCZQEhPXmzk8kb0ttN2UTCQS3nF+aHtFpeqTn6nzgojWHY+pXzN3bHkRouKX+ak5gbII5kD0+32dUyCy+cbZReezA4hkfsflEt1Zt8c74rEcNdsYJH8RcmZMm0pML7BO+JnGnrFM2MKV0CgWNYooyZp2mXeru9NMPYoTw5amJoq3YST4lZ8evYxmrqtCsgpuqMLYYC9ljWhbBa4hcC2LxrM4iXHgQe1cGw+qMibteuqxNoz/nflqO5gCNVY8/abr6hJkedlFOoQuPQOeJ4WMzRSQumvgdxPENjTQ8q/PKHChYbcwy/PJsr9CxKEeyeTa5B1w+lBvUdy1LDMJBHIhpP3ADDYHXS0jENFC3YS7ljTimvmNx9FaupEdvqc/PQh/VpTP+vntfugAGBPy1kYy+4QWizoJcdu70IamRuYfulB9tYPd4gsdgUo5tRHBdZ2Wf5WJRlA75nXAn/cjt0TsIh15QRbiNnRFHFacQnAVHNMM9+u4pAIbgu6iE1Y6cVWpalDRWLg1LsGFRJyP2rAGHNKhXbRwDHax8TMqxl1MOV86fBOoSYKYWZ36D5cwKw0Madf0n+cZ5p4dzxRMS1Y0wfGhoa2HYlbd9K1hex+CIt5JqRaGgjAZt55PCUD54ygcSJ1lcNuanJuWwYBLEkQa2snh2rWKaKvwD5aX5l1dwAc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: NorakGithub/django-model-controller
