language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: jjxNFIHrMdgNn2sksyfWpVtB8U/G4H3I3xcfIbFdsUNihlNRxFhCGXyfU2xvP/v8OljSvctqq4vaXExNtpFeuV27FjHWJ9uN+tr64Nyolm6/fkn3ZDUIufNTHq+y3HDilan4ne7bq6tt2m+I+Qtc/WxqZKkmc+xdPSfALAVDeC1bN4DUhwAkGNAlUiy1IKfMnU+6Oom/7iT8+8oUSNEMcoFe6jNV0WAouXl7O4i3IfzJgNdarV5W6QZijW2wlevvZfpURHbQi4aGMLWD3VszB69eG4pNmRoR1J6X+oYEp+s/edHP3si+i5+/CJrGwxvyTdwHCpRbCQFyNSm0zFVm8TgMPn2OgJESU4VnQNqs+ISv78WzsgZeDesvhGWtHb3mSHvRQkH77o8oXX9SuCjf7G9MG7v3yJyHXAccORcsqsQyO7yGlgjj+1ITrLJRqpNuCNl5zLndeKsEZNu/++/ZEKsGE6xmczWK/20e6QAQbHdcuW5/PzulJH8EO8BE/sduiMGV9y92DZJsn9/rwlMSYTUIq+DY+3AW1ZxI98H+eFLcAI8iVlQORdYf+aDai7sJCj/y9hM90RZ6hCO7POUkgVSMa7ApQX1fqL4ZGJH0OKZveASIU3/ICDPb9H4dsYlxiDbXXAXLacIMwa/lPuhjjLE36lYCfvW+55Wuas5VZzg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: NorakGithub/django-model-controller
